#!/usr/bin/env php
<?php

use AcMarche\Theme\Command\MeiliCommand;
use AcMarche\Theme\Command\PivotCommand;
use Symfony\Component\Console\Application;
use Symfony\Component\Dotenv\Dotenv;

require __DIR__.'/vendor/autoload.php';

$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

$application = new Application();

$application->add(new PivotCommand());
$application->add(new MeiliCommand());

$application->run();